import { Header } from '@/components/shared';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'next-pizza',
	description: 'Generated by create next app',
};

export default function HomeLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>	
			<main className='min-h-screen'>
				<Header />
				{children}
				{modal}
			</main>
			</body>
		</html>
	);
}
